# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 900ce160939e34093c0bc324290877b9ff9bef4698cfb56173082d254dc31651662a8b198524d182f788049a36f8235e3c2110e2ee20f960ab758dde5c6beecf

test:
  secret_key_base: 0526f4989f9a617bec4615a186d9e4fad6fe50ea498ca267341e9fc83cecab430dc9f39b7392aa47298cbfd40b1d54619aff561c0834b2bc0665b33be91ab696

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
